<?php


/**
 * pull recommended users from `kendra_match_recommender_out_user_to_user` for the current user
 */
function _kendra_match_recommender_recommend_users($query = NULL, $filter = NULL, $sort = NULL, $page = 0, $page_size = 3) {
  $results     = array();
  $safe_query  = check_plain($query);
  $safe_sort   = check_plain($sort);
  $safe_filter = check_plain($filter);

  //@FIXME: override paging vars, that appear to be NULL
  $page = 0;
  $page_size = 3;

  global $user;
  $uid = $user->uid;

  $sql = sprintf("SELECT users.name, recommended_uid FROM {kendra_match_recommender_out_user_to_user}
       INNER JOIN users ON users.uid=kendra_match_recommender_out_user_to_user.uid                                                                                                                                                                      
       WHERE users.uid = %d and status = 1 
       ORDER BY weight DESC, time DESC LIMIT %s, %s
       ", $uid, $page, $page_size);

  $result = db_query($sql);

  $uids = array();

  foreach ($result as $node) {
    $uids[] = $node->recommended_uid;
  }

  $results = user_load_multiple($uids);

  return $results;
}

/**
 * pull recommended content from `kendra_match_recommender_out_user_to_item` for the current user
 */
function _kendra_match_recommender_recommend_content($query = NULL, $filter = NULL, $sort = NULL, $page = 0, $page_size = 3) {
  $results     = array();
  $safe_query  = check_plain($query);
  $safe_sort   = check_plain($sort);
  $safe_filter = check_plain($filter);

  //@FIXME: override paging vars, that appear to be NULL
  $page = 0;
  $page_size = 3;

  global $user;
  $uid = $user->uid;

  $sql = sprintf("SELECT DISTINCT recommended_nid FROM {kendra_match_recommender_out_user_to_item}
      WHERE uid = %d AND NOT ISNULL(recommended_nid)
      ORDER BY weight
      DESC, time DESC LIMIT %s, %s
      ", $uid, $page, $page_size);

  $result = db_query($sql);

  foreach ($result as $node) {
    $results[] = node_load($node->recommended_nid);
  }

  return $results;
}

/**
 * search users
 */
function _kendra_match_recommender_search_users($query = NULL, $filter = NULL, $sort = NULL, $page = 0, $page_size = 10) {
  $results     = array();
  $safe_query  = check_plain($query);
  $safe_sort   = check_plain($sort);
  $safe_filter = check_plain($filter);

  // Invoke the search hook to generate results
  // @todo incorporate $safe_sort, $safe_filter
  $results = module_invoke('user', 'search_execute', $safe_query);
  return $results;
}

/**
 * search content
 */
function _kendra_match_recommender_search_content($query = NULL, $filter = NULL, $sort = NULL, $page = 0, $page_size = 10) {
  $results = array();
  $search_allowed_types = array('mediaitem');
  $safe_query = check_plain($query);
  $safe_sort = check_plain($sort);
  $safe_filter = check_plain($filter);

  // restrict content types in search results
  $safe_query .= ' type:' . join(',', $search_allowed_types);
  
  // Invoke the search hook to generate results.
  $results = module_invoke('node', 'search_execute', $safe_query);
  return $results;
}
